[build-system]
# Pin setuptools to v64, which changes how editable wheels are built/installed, which mypy doesn't understand.
requires = ["setuptools==64.0.3", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"
